### ISSUE TITLE
Command `tojunit` failed to install, error: exit status 9

### ISSUE THREAD

**Issue by veronicagiraldo** [BirmacherAkos/bitrise-step-xctest-html-report#22]
Hi--

I am having issues with bitrise-step-xctest-html-report, this step will randomly fail and says, 

"End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive."
  
  and Command `tojunit` failed to install, error: exit status 9
  
  It seems like there is something wrong with the .zip files. What can I do to fix this step please? and what other information do you need to trouble shoot this issue. 

Thank you 

Veronica

**Comment by ochalet-wp** [comment]
Hi @veronicagiraldo ,

My team and I use this step and have come across the same issue.

While we all wait for a fix, there is a workaround which is to downgrade the version of the `XCTestHTMLReport` tool that the step is trying to install to version `2.0.0`

```
- xctest-html-report@1:
        inputs:
        - output_dir: "$BITRISE_SOURCE_DIR/my-project/"
        - version: "2.0.0"
```
